name: C/C++ CI

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Configure
      run: cmake .
    - name: Build
      run: make -j2
    - name: Unit Tests
      run: ctest -V
    - name: Archive Executable
      uses: actions/upload-artifact@master
      with:
        name: project_two
        path: bin/project_two
    # - name: Performance Tests
    #   run: make perf
    # - name: Archive Performance Output
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: performance-data
    #     path: performance
