name: C/C++ CI

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake .
    - name: Build
      run: make -j2
    - name: Unit Tests
      run: ctest -V
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: project_two
        path: bin/project_two
